accounts:
  - name: alice
    coins: ["20000token", "200000000000stake"]
  - name: bob
    coins: ["10000token", "100000000000stake"]
  - name: carl
    coins: ["20000token", "200000000stake"]
    mnemonic: "dragon shrimp eyebrow guide vendor cover find vital draw catalog coconut venture lyrics supply almost skull apple oil apology illegal apple sugar charge ring"
validator:
  name: alice
  staked: "20000000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  config:
    fast_sync: false
    log_level: error
    p2p:
      allow_duplicate_ip: true
    consensus: #set the block time:
      timeout_commit: "2s" 
  client:
    broadcast-mode: "sync"
genesis: 
  consensus_params:
    block:
      time_iota_ms: "1000" #milliseconds
  app_state:
    slashing:
      params:
        signed_blocks_window: 10
    staking:
      params:
        unbonding_time: "60s"  # seconds