version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000000stake
- name: bob
  coins:
  - 10000token
  - 100000000000stake
- name: carl
  coins:
  - 20000token
  - 200000000stake
  mnemonic: dragon shrimp eyebrow guide vendor cover find vital draw catalog coconut
    venture lyrics supply almost skull apple oil apology illegal apple sugar charge
    ring
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    slashing:
      params:
        signed_blocks_window: 10
    staking:
      params:
        unbonding_time: 60s
  consensus_params:
    block:
      time_iota_ms: "1000"
validators:
- name: alice
  bonded: 20000000000stake
  config:
    consensus:
      timeout_commit: 2s
    fast_sync: false
    log_level: error
    p2p:
      allow_duplicate_ip: true
  client:
    broadcast-mode: block
