// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slashrefund/unbonding_deposit_entry.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UnbondingDepositEntry struct {
	CreationHeight int64                                  `protobuf:"varint,1,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	CompletionTime time.Time                              `protobuf:"bytes,2,opt,name=completion_time,json=completionTime,proto3,stdtime" json:"completion_time"`
	InitialBalance github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=initial_balance,json=initialBalance,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"initial_balance"`
	Balance        github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=balance,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"balance"`
}

func (m *UnbondingDepositEntry) Reset()         { *m = UnbondingDepositEntry{} }
func (m *UnbondingDepositEntry) String() string { return proto.CompactTextString(m) }
func (*UnbondingDepositEntry) ProtoMessage()    {}
func (*UnbondingDepositEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06d610f9a1608f3, []int{0}
}
func (m *UnbondingDepositEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingDepositEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingDepositEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingDepositEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingDepositEntry.Merge(m, src)
}
func (m *UnbondingDepositEntry) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingDepositEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingDepositEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingDepositEntry proto.InternalMessageInfo

func (m *UnbondingDepositEntry) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *UnbondingDepositEntry) GetCompletionTime() time.Time {
	if m != nil {
		return m.CompletionTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*UnbondingDepositEntry)(nil), "madeinblock.slashrefund.slashrefund.UnbondingDepositEntry")
}

func init() {
	proto.RegisterFile("slashrefund/unbonding_deposit_entry.proto", fileDescriptor_f06d610f9a1608f3)
}

var fileDescriptor_f06d610f9a1608f3 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xcd, 0xb4, 0x1f, 0x9f, 0x1a, 0xa1, 0x85, 0xa0, 0x50, 0xbb, 0x48, 0x8a, 0x82, 0xd6, 0x45,
	0x26, 0xa0, 0x2b, 0xb7, 0x41, 0xa1, 0x2e, 0xdc, 0x54, 0x45, 0x70, 0x13, 0xf2, 0x33, 0x4d, 0x86,
	0x26, 0x73, 0x43, 0x66, 0x02, 0xf6, 0x2d, 0xfa, 0x2c, 0x3e, 0x45, 0x97, 0x5d, 0x8a, 0x8b, 0x2a,
	0xed, 0x8b, 0x48, 0x66, 0x12, 0xcc, 0xda, 0x55, 0xee, 0xdf, 0x39, 0xf7, 0x64, 0xce, 0xd5, 0x2f,
	0x79, 0xea, 0xf3, 0xa4, 0x20, 0xb3, 0x92, 0x45, 0x4e, 0xc9, 0x02, 0x60, 0x11, 0x65, 0xb1, 0x17,
	0x91, 0x1c, 0x38, 0x15, 0x1e, 0x61, 0xa2, 0x58, 0xe0, 0xbc, 0x00, 0x01, 0xc6, 0x59, 0xe6, 0x47,
	0x84, 0xb2, 0x20, 0x85, 0x70, 0x8e, 0x5b, 0xb0, 0x76, 0x3c, 0x3c, 0x8a, 0x21, 0x06, 0x39, 0xef,
	0x54, 0x91, 0x82, 0x0e, 0xad, 0x18, 0x20, 0x4e, 0x89, 0x23, 0xb3, 0xa0, 0x9c, 0x39, 0x82, 0x66,
	0x84, 0x0b, 0x3f, 0xcb, 0xeb, 0x81, 0x93, 0x10, 0x78, 0x06, 0xdc, 0x53, 0x48, 0x95, 0xa8, 0xd6,
	0xe9, 0x7b, 0x47, 0x3f, 0x7e, 0x6e, 0x84, 0xdd, 0x2a, 0x5d, 0x77, 0x95, 0x2c, 0xe3, 0x42, 0xef,
	0x87, 0x05, 0xf1, 0x05, 0x05, 0xe6, 0x25, 0x84, 0xc6, 0x89, 0x18, 0xa0, 0x11, 0x1a, 0x77, 0xa7,
	0xbd, 0xa6, 0x3c, 0x91, 0x55, 0xe3, 0x41, 0xef, 0x87, 0x90, 0xe5, 0x29, 0x91, 0xa3, 0xd5, 0xee,
	0x41, 0x67, 0x84, 0xc6, 0x87, 0x57, 0x43, 0xac, 0x84, 0xe1, 0x46, 0x18, 0x7e, 0x6a, 0x84, 0xb9,
	0xfb, 0xab, 0x8d, 0xa5, 0x2d, 0xbf, 0x2c, 0x34, 0xed, 0xfd, 0x82, 0xab, 0xb6, 0xf1, 0xa2, 0xf7,
	0x29, 0xa3, 0x82, 0xfa, 0xa9, 0x17, 0xf8, 0xa9, 0xcf, 0x42, 0x32, 0xe8, 0x8e, 0xd0, 0xf8, 0xc0,
	0xc5, 0x15, 0xe4, 0x73, 0x63, 0x9d, 0xc7, 0x54, 0x24, 0x65, 0x80, 0x43, 0xc8, 0xea, 0x7f, 0xa9,
	0x3f, 0x36, 0x8f, 0xe6, 0x8e, 0x58, 0xe4, 0x84, 0xe3, 0x7b, 0x26, 0xa6, 0xbd, 0x9a, 0xc6, 0x55,
	0x2c, 0xc6, 0x44, 0xdf, 0x6b, 0x08, 0xff, 0xfd, 0x89, 0xb0, 0x81, 0xbb, 0x8f, 0xab, 0xad, 0x89,
	0xd6, 0x5b, 0x13, 0x7d, 0x6f, 0x4d, 0xb4, 0xdc, 0x99, 0xda, 0x7a, 0x67, 0x6a, 0x1f, 0x3b, 0x53,
	0x7b, 0xbd, 0x69, 0x51, 0x55, 0x86, 0xda, 0x94, 0xd9, 0xd2, 0x52, 0x47, 0xda, 0x68, 0xd7, 0xa7,
	0xf0, 0xe6, 0xb4, 0x0f, 0x43, 0x6e, 0x08, 0xfe, 0xcb, 0x57, 0xba, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x21, 0xee, 0xf5, 0x60, 0x34, 0x02, 0x00, 0x00,
}

func (m *UnbondingDepositEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingDepositEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingDepositEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Balance.Size()
		i -= size
		if _, err := m.Balance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.InitialBalance.Size()
		i -= size
		if _, err := m.InitialBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.CreationHeight != 0 {
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUnbondingDepositEntry(dAtA []byte, offset int, v uint64) int {
	offset -= sovUnbondingDepositEntry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UnbondingDepositEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreationHeight != 0 {
		n += 1 + sovUnbondingDepositEntry(uint64(m.CreationHeight))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	l = m.InitialBalance.Size()
	n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	l = m.Balance.Size()
	n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	return n
}

func sovUnbondingDepositEntry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUnbondingDepositEntry(x uint64) (n int) {
	return sovUnbondingDepositEntry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UnbondingDepositEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUnbondingDepositEntry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingDepositEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingDepositEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUnbondingDepositEntry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUnbondingDepositEntry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUnbondingDepositEntry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUnbondingDepositEntry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUnbondingDepositEntry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUnbondingDepositEntry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUnbondingDepositEntry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUnbondingDepositEntry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUnbondingDepositEntry = fmt.Errorf("proto: unexpected end of group")
)
