// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slashrefund/unbonding_deposit_entry.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UnbondingDepositEntry struct {
	CreationHeight int32  `protobuf:"varint,1,opt,name=creationHeight,proto3" json:"creationHeight,omitempty"`
	CompletionTime string `protobuf:"bytes,2,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	InitialBalance string `protobuf:"bytes,3,opt,name=initialBalance,proto3" json:"initialBalance,omitempty"`
	Balance        string `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *UnbondingDepositEntry) Reset()         { *m = UnbondingDepositEntry{} }
func (m *UnbondingDepositEntry) String() string { return proto.CompactTextString(m) }
func (*UnbondingDepositEntry) ProtoMessage()    {}
func (*UnbondingDepositEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06d610f9a1608f3, []int{0}
}
func (m *UnbondingDepositEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingDepositEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingDepositEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingDepositEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingDepositEntry.Merge(m, src)
}
func (m *UnbondingDepositEntry) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingDepositEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingDepositEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingDepositEntry proto.InternalMessageInfo

func (m *UnbondingDepositEntry) GetCreationHeight() int32 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *UnbondingDepositEntry) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *UnbondingDepositEntry) GetInitialBalance() string {
	if m != nil {
		return m.InitialBalance
	}
	return ""
}

func (m *UnbondingDepositEntry) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func init() {
	proto.RegisterType((*UnbondingDepositEntry)(nil), "madeinblock.slashrefund.slashrefund.UnbondingDepositEntry")
}

func init() {
	proto.RegisterFile("slashrefund/unbonding_deposit_entry.proto", fileDescriptor_f06d610f9a1608f3)
}

var fileDescriptor_f06d610f9a1608f3 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0xce, 0x49, 0x2c,
	0xce, 0x28, 0x4a, 0x4d, 0x2b, 0xcd, 0x4b, 0xd1, 0x2f, 0xcd, 0x4b, 0xca, 0xcf, 0x4b, 0xc9, 0xcc,
	0x4b, 0x8f, 0x4f, 0x49, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xaa, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xce, 0x4d, 0x4c, 0x49, 0xcd, 0xcc, 0x4b, 0xca, 0xc9,
	0x4f, 0xce, 0xd6, 0x43, 0xd2, 0x86, 0xcc, 0x56, 0x5a, 0xc9, 0xc8, 0x25, 0x1a, 0x0a, 0x33, 0xc6,
	0x05, 0x62, 0x8a, 0x2b, 0xc8, 0x10, 0x21, 0x35, 0x2e, 0xbe, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xcc,
	0xfc, 0x3c, 0x8f, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x34,
	0x51, 0xb0, 0xba, 0xfc, 0xdc, 0x82, 0x9c, 0x54, 0x90, 0x58, 0x48, 0x66, 0x6e, 0xaa, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x9a, 0x28, 0x48, 0x5d, 0x66, 0x5e, 0x66, 0x49, 0x66, 0x62, 0x8e,
	0x53, 0x62, 0x4e, 0x62, 0x5e, 0x72, 0xaa, 0x04, 0x33, 0x44, 0x1d, 0xaa, 0xa8, 0x90, 0x04, 0x17,
	0x7b, 0x12, 0x54, 0x01, 0x0b, 0x58, 0x01, 0x8c, 0xeb, 0x14, 0x7c, 0xe2, 0x91, 0x1c, 0xe3, 0x85,
	0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3,
	0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x96, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9,
	0xfa, 0x20, 0x5f, 0xeb, 0x66, 0xe6, 0xe9, 0x82, 0xfd, 0xad, 0x0f, 0xf6, 0xab, 0x2e, 0x34, 0xbc,
	0x2a, 0xf4, 0x91, 0x43, 0xaf, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x1c, 0x58, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x08, 0x62, 0x99, 0x59, 0x01, 0x00, 0x00,
}

func (m *UnbondingDepositEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingDepositEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingDepositEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balance) > 0 {
		i -= len(m.Balance)
		copy(dAtA[i:], m.Balance)
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(len(m.Balance)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.InitialBalance) > 0 {
		i -= len(m.InitialBalance)
		copy(dAtA[i:], m.InitialBalance)
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(len(m.InitialBalance)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CompletionTime) > 0 {
		i -= len(m.CompletionTime)
		copy(dAtA[i:], m.CompletionTime)
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(len(m.CompletionTime)))
		i--
		dAtA[i] = 0x12
	}
	if m.CreationHeight != 0 {
		i = encodeVarintUnbondingDepositEntry(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUnbondingDepositEntry(dAtA []byte, offset int, v uint64) int {
	offset -= sovUnbondingDepositEntry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UnbondingDepositEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreationHeight != 0 {
		n += 1 + sovUnbondingDepositEntry(uint64(m.CreationHeight))
	}
	l = len(m.CompletionTime)
	if l > 0 {
		n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	}
	l = len(m.InitialBalance)
	if l > 0 {
		n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	}
	l = len(m.Balance)
	if l > 0 {
		n += 1 + l + sovUnbondingDepositEntry(uint64(l))
	}
	return n
}

func sovUnbondingDepositEntry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUnbondingDepositEntry(x uint64) (n int) {
	return sovUnbondingDepositEntry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UnbondingDepositEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUnbondingDepositEntry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingDepositEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingDepositEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompletionTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUnbondingDepositEntry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUnbondingDepositEntry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUnbondingDepositEntry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUnbondingDepositEntry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDepositEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUnbondingDepositEntry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUnbondingDepositEntry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUnbondingDepositEntry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUnbondingDepositEntry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUnbondingDepositEntry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUnbondingDepositEntry = fmt.Errorf("proto: unexpected end of group")
)
