// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slashrefund/unbonding_deposit.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UnbondingDeposit struct {
	Id             uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UnbondingStart time.Time `protobuf:"bytes,2,opt,name=unbondingStart,proto3,stdtime" json:"unbondingStart"`
	Deposit        *Deposit  `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit,omitempty"`
}

func (m *UnbondingDeposit) Reset()         { *m = UnbondingDeposit{} }
func (m *UnbondingDeposit) String() string { return proto.CompactTextString(m) }
func (*UnbondingDeposit) ProtoMessage()    {}
func (*UnbondingDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b62f420100ad0b, []int{0}
}
func (m *UnbondingDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingDeposit.Merge(m, src)
}
func (m *UnbondingDeposit) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingDeposit proto.InternalMessageInfo

func (m *UnbondingDeposit) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnbondingDeposit) GetUnbondingStart() time.Time {
	if m != nil {
		return m.UnbondingStart
	}
	return time.Time{}
}

func (m *UnbondingDeposit) GetDeposit() *Deposit {
	if m != nil {
		return m.Deposit
	}
	return nil
}

func init() {
	proto.RegisterType((*UnbondingDeposit)(nil), "madeinblock.slashrefund.slashrefund.UnbondingDeposit")
}

func init() {
	proto.RegisterFile("slashrefund/unbonding_deposit.proto", fileDescriptor_00b62f420100ad0b)
}

var fileDescriptor_00b62f420100ad0b = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xbf, 0x4e, 0x84, 0x30,
	0x1c, 0xa6, 0x68, 0xd4, 0x60, 0x72, 0x31, 0xc4, 0x01, 0x19, 0xca, 0xc5, 0x5b, 0x6e, 0x90, 0x36,
	0xd1, 0xc9, 0xf5, 0x62, 0x9c, 0x9c, 0x38, 0x5d, 0x5c, 0x4c, 0xb9, 0xf6, 0x7a, 0x8d, 0xd0, 0x12,
	0x28, 0x89, 0xf7, 0x16, 0xf7, 0x38, 0x3e, 0xc2, 0x8d, 0x37, 0x3a, 0xa9, 0x81, 0x17, 0x31, 0x57,
	0xc0, 0x20, 0x93, 0xdb, 0xaf, 0xf9, 0xfa, 0xfd, 0x75, 0x26, 0x45, 0x42, 0x8a, 0x55, 0xce, 0x96,
	0xa5, 0xa4, 0xb8, 0x94, 0xb1, 0x92, 0x54, 0x48, 0xfe, 0x42, 0x59, 0xa6, 0x0a, 0xa1, 0x51, 0x96,
	0x2b, 0xad, 0xdc, 0x49, 0x4a, 0x28, 0x13, 0x32, 0x4e, 0xd4, 0xe2, 0x15, 0xf5, 0x08, 0xfd, 0xdb,
	0x3f, 0xe7, 0x8a, 0x2b, 0xf3, 0x1f, 0xef, 0xaf, 0x86, 0xea, 0x5f, 0x70, 0xa5, 0x78, 0xc2, 0xb0,
	0x79, 0xc5, 0xe5, 0x12, 0x13, 0xb9, 0x6e, 0x21, 0x38, 0x84, 0x68, 0x99, 0x13, 0x2d, 0x94, 0x6c,
	0xf1, 0x60, 0x88, 0x6b, 0x91, 0xb2, 0x42, 0x93, 0x34, 0xeb, 0xb4, 0xfb, 0xd9, 0xff, 0x24, 0xbe,
	0x7c, 0x07, 0xce, 0xd9, 0x53, 0xd7, 0xe6, 0xae, 0x81, 0xdc, 0x91, 0x63, 0x0b, 0xea, 0x81, 0x31,
	0x98, 0x1e, 0x46, 0xb6, 0xa0, 0xee, 0x83, 0x33, 0xfa, 0x6d, 0x3c, 0xd7, 0x24, 0xd7, 0x9e, 0x3d,
	0x06, 0xd3, 0xd3, 0x6b, 0x1f, 0x35, 0xce, 0xa8, 0x73, 0x46, 0x8f, 0x9d, 0xf3, 0xec, 0x64, 0xfb,
	0x19, 0x58, 0x9b, 0xaf, 0x00, 0x44, 0x03, 0xae, 0x7b, 0xef, 0x1c, 0xb7, 0x19, 0xbc, 0x03, 0x23,
	0x73, 0x85, 0xfe, 0x31, 0x1b, 0x6a, 0xc3, 0x45, 0x1d, 0x79, 0x36, 0xdf, 0x56, 0x10, 0xec, 0x2a,
	0x08, 0xbe, 0x2b, 0x08, 0x36, 0x35, 0xb4, 0x76, 0x35, 0xb4, 0x3e, 0x6a, 0x68, 0x3d, 0xdf, 0x72,
	0xa1, 0x57, 0x65, 0x8c, 0x16, 0x2a, 0xc5, 0x7b, 0xe9, 0x50, 0xc8, 0xd0, 0x88, 0x63, 0x23, 0x18,
	0xb6, 0x4b, 0xbc, 0xe1, 0xfe, 0x2e, 0x7a, 0x9d, 0xb1, 0x22, 0x3e, 0x32, 0x55, 0x6e, 0x7e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x1e, 0x50, 0xe7, 0xc7, 0xef, 0x01, 0x00, 0x00,
}

func (m *UnbondingDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Deposit != nil {
		{
			size, err := m.Deposit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUnbondingDeposit(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.UnbondingStart, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.UnbondingStart):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintUnbondingDeposit(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintUnbondingDeposit(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUnbondingDeposit(dAtA []byte, offset int, v uint64) int {
	offset -= sovUnbondingDeposit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UnbondingDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovUnbondingDeposit(uint64(m.Id))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.UnbondingStart)
	n += 1 + l + sovUnbondingDeposit(uint64(l))
	if m.Deposit != nil {
		l = m.Deposit.Size()
		n += 1 + l + sovUnbondingDeposit(uint64(l))
	}
	return n
}

func sovUnbondingDeposit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUnbondingDeposit(x uint64) (n int) {
	return sovUnbondingDeposit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UnbondingDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUnbondingDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUnbondingDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.UnbondingStart, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbondingDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUnbondingDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUnbondingDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Deposit == nil {
				m.Deposit = &Deposit{}
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUnbondingDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUnbondingDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUnbondingDeposit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUnbondingDeposit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbondingDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUnbondingDeposit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUnbondingDeposit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUnbondingDeposit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUnbondingDeposit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUnbondingDeposit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUnbondingDeposit = fmt.Errorf("proto: unexpected end of group")
)
