package slashrefund

import (
	"fmt"

	sdk "github.com/cosmos/cosmos-sdk/types"

	slashingtypes "github.com/cosmos/cosmos-sdk/x/slashing/types"
	"github.com/made-in-block/slash-refund/x/slashrefund/keeper"
	"github.com/made-in-block/slash-refund/x/slashrefund/types"
	abci "github.com/tendermint/tendermint/abci/types"
)

func BeginBlocker(ctx sdk.Context, req abci.RequestBeginBlock, k keeper.Keeper) {

	logger := k.Logger(ctx)
	logger.Error("Height", "height", ctx.BlockHeight())

	//Handle slashing event
	events := ctx.EventManager().Events()
	//Events()

	// Iterate all events in this block
	for _, event := range events {
		// Check if we have a slashing event
		if event.Type == slashingtypes.EventTypeSlash && string(event.Attributes[0].GetKey()) != "jailed" {
			//the second if is the slash event generated by Jail and has
			//no information to be used for the refund.
			// TODO: handle jail slash event better.
			logger.Error(fmt.Sprintf("|_ event: %s", event.Type))
			logger.Error("  |_ I'ts slashing time!")
			k.HandleRefundsFromSlash(ctx, event)
		}
	}
}

func EndBlocker(ctx sdk.Context, req abci.RequestEndBlock, k keeper.Keeper) []types.DVPair {

	logger := k.Logger(ctx)
	logger.Error("|_ End blocker")

	//Handle unbonding dequeue
	matureUnbonds := k.BlockUnbondingDepositUpdates(ctx)
	if matureUnbonds != nil {
		logger.Error("    |_ found and processed mature unbonds")
	}

	// TODO: Handle removed validator's deposit
	/*
		// get validator
		_, found = k.stakingKeeper.GetValidator(ctx, valAddr)
		if !found {
			return issuedTokensAmt, stakingtypes.ErrNoValidatorFound
		}
	*/

	return matureUnbonds
}
